version: '3.8'
services:
  ray-head:
    image: rayproject/ray:latest
    container_name: ray-head
    command: >
      ray start --head
      --node-ip-address=0.0.0.0
      --port=10030
      --object-manager-port=10031
      --node-manager-port=10032
      --dashboard-host=0.0.0.0
      --dashboard-port=10033
      --ray-client-server-port=10034
      --min-worker-port=10035
      --max-worker-port=10065
      --temp-dir=/ray-temp
      --block
    ports:
      - "10030:10030"  # GCS server
      - "10031:10031"  # Object manager
      - "10032:10032"  # Node manager
      - "10033:10033"  # Dashboard
      - "10034:10034"  # Ray client server
      - "10035-10065:10035-10065"  # Worker ports (head)
    environment:
      - RAY_DISABLE_IMPORT_WARNING=1
    volumes:
      - ./docker/ray-temp:/ray-temp
    restart: unless-stopped
    networks:
      - ray-network

  ray-worker-gpu-1:
    image: rayproject/ray:latest-gpu
    container_name: ray-worker-gpu-1
    command: >
      ray start
      --address=ray-head:10030
      --object-manager-port=10071
      --node-manager-port=10072
      --min-worker-port=10075
      --max-worker-port=10100
      --temp-dir=/ray-temp
      --block
    ports:
      - "10071:10071"  # Object manager
      - "10072:10072"  # Node manager
      - "10075-10100:10075-10100"  # Worker ports
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - RAY_DISABLE_IMPORT_WARNING=1
    volumes:
      - ./docker/ray-temp-worker-1:/ray-temp
    restart: unless-stopped
    depends_on:
      - ray-head
    networks:
      - ray-network

  ray-worker-gpu-2:
    image: rayproject/ray:latest-gpu
    container_name: ray-worker-gpu-2
    command: >
      ray start
      --address=ray-head:10030
      --object-manager-port=10101
      --node-manager-port=10102
      --min-worker-port=10105
      --max-worker-port=10130
      --temp-dir=/ray-temp
      --block
    ports:
      - "10101:10101"  # Object manager
      - "10102:10102"  # Node manager
      - "10105-10130:10105-10130"  # Worker ports
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "1"
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=1
      - RAY_DISABLE_IMPORT_WARNING=1
    volumes:
      - ./docker/ray-temp-worker-2:/ray-temp
    restart: unless-stopped
    depends_on:
      - ray-head
    networks:
      - ray-network

volumes:
  ray_logs:

networks:
  ray-network:
    driver: bridge